// <auto-generated />
namespace MMonitorLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_some_fields_to_source : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_some_fields_to_source));
        
        string IMigrationMetadata.Id
        {
            get { return "201709231406174_added_some_fields_to_source"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
