// <auto-generated />
namespace MMonitorLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_index_for_url_hash1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_index_for_url_hash1));
        
        string IMigrationMetadata.Id
        {
            get { return "201709222018002_added_index_for_url_hash1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
